name: .NET CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Stable release

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Run Unit Tests
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Output - ${{ matrix.configuration }}
        path: |
          **/bin/${{ matrix.configuration }}/
          **/obj/${{ matrix.configuration }}/

